let songs = [
  {
    name: "song 1",
    path: "assets/audio/audio_1.mp3",
    artist: "Artist 1",
    cover: "assets/images/1.jpg",
  },
  {
    name: "song 2",
    path: "assets/audio/audio_2.mp3",
    artist: "Artist 2",
    cover: "assets/images/2.jpg",
  },
  {
    name: "song 3",
    path: "assets/audio/audio_3.mp3",
    artist: "Artist 3",
    cover: "assets/images/3.jpg",
  },
  {
    name: "song 4",
    path: "assets/audio/audio_4.mp3",
    artist: "Artist 4",
    cover: "assets/images/4.jpg",
  },
  {
    name: "song 5",
    path: "assets/audio/audio_5.mp3",
    artist: "Artist 5",
    cover: "assets/images/5.jpg",
  },
  {
    name: "song 6",
    path: "assets/audio/audio_6.mp3",
    artist: "Artist 6",
    cover: "assets/images/6.jpg",
  },
  {
    name: "song 7",
    path: "assets/audio/audio_7.mp3",
    artist: "Artist 7",
    cover: "assets/images/7.jpg",
  },
  {
    name: "song 8",
    path: "assets/audio/audio_8.mp3",
    artist: "Artist 8",
    cover: "assets/images/8.jpg",
  },
  {
    name: "song 9",
    path: "assets/audio/audio_9.mp3",
    artist: "Artist 9",
    cover: "assets/images/9.jpg",
  },
  {
    name: "song 10",
    path: "assets/audio/audio_10.mp3",
    artist: "Artist 10",
    cover: "assets/images/10.jpg",
  },
  {
    name: "song 11",
    path: "assets/audio/audio_11.mp3",
    artist: "Artist 11",
    cover: "assets/images/11.jpg",
  },
  {
    name: "song 12",
    path: "assets/audio/audio_12.mp3",
    artist: "Artist 12",
    cover: "assets/images/12.jpg",
  },
  {
    name: "song 13",
    path: "assets/audio/audio_13.mp3",
    artist: "Artist 13",
    cover: "assets/images/13.jpg",
  },
  {
    name: "song 14",
    path: "assets/audio/audio_14.mp3",
    artist: "Artist 14",
    cover: "assets/images/14.jpg",
  },
];
